version: "3.4"
services:
 qbittorrent_bot:
  build: .
  image: qbittorrent_bot
  privileged: true
  restart: always
  tty: true
  stdin_open: true
  deploy:
    update_config:
      order: start-first
  container_name: qbittorrent_bot
  volumes:
    - "/volume1/docker/qBittorrentBot:/app/config"
